<?php
/**
 * Live Facebook + Instagram feed for the AME Bazaar homepage.
 *
 * The browser talks only to the same-origin WordPress REST proxy. The proxy
 * reads the public feed from the existing Google Apps Script, keeping Meta
 * credentials out of WordPress and the browser.
 *
 * @package Ame_Bazaar
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$facebook_url  = 'https://www.facebook.com/AMETTBAZAAR';
$instagram_url = 'https://www.instagram.com/ame_bazaar/';
$feed_api_url  = rest_url( 'ame/v1/social-feed' );
?>

<section class="ame-social-feed-section" aria-labelledby="ame-social-feed-title" data-social-feed-api="<?php echo esc_url( $feed_api_url ); ?>">
	<div class="ame-bazaar-container">
		<div class="ame-social-feed-header">
			<div class="ame-social-feed-live"><span></span> LIVE FROM AME BAZAAR</div>
			<h2 id="ame-social-feed-title" class="ame-h2">What's New on Facebook &amp; Instagram</h2>
			<p class="ame-body">Real posts from our official social pages — automatically refreshed with the latest arrivals, looks and showroom updates.</p>
		</div>

		<div class="ame-social-feed-grid">
			<article class="ame-social-feed-card" data-social-card="facebook">
				<header class="ame-social-feed-card-head">
					<div class="ame-social-feed-brand"><div class="ame-social-feed-brand-icon facebook">f</div><div><strong data-profile-name>AME Bazaar</strong><small>Facebook</small></div></div>
					<a class="ame-social-feed-follow facebook" href="<?php echo esc_url( $facebook_url ); ?>" target="_blank" rel="noopener noreferrer">Follow Page</a>
				</header>
				<div class="ame-social-feed-facebook-profile"><div class="ame-social-feed-facebook-cover"></div><div class="ame-social-feed-facebook-profile-row"><div class="ame-social-feed-profile-icon facebook">f</div><div><strong data-profile-title>AME Bazaar</strong><small data-profile-stats>Official Facebook Page</small></div></div></div>
			<div class="ame-social-feed-posts" data-posts><div class="ame-social-feed-loading">Loading live Facebook posts…</div></div>
			</article>

			<article class="ame-social-feed-card" data-social-card="instagram">
				<header class="ame-social-feed-card-head">
					<div class="ame-social-feed-brand"><div class="ame-social-feed-brand-icon instagram">◎</div><div><strong data-profile-name>ame_bazaar</strong><small>Instagram</small></div></div>
					<a class="ame-social-feed-follow instagram" href="<?php echo esc_url( $instagram_url ); ?>" target="_blank" rel="noopener noreferrer">Follow</a>
				</header>
				<div class="ame-social-feed-instagram-profile"><div class="ame-social-feed-profile-icon instagram">◎</div><div class="ame-social-feed-instagram-details"><strong data-profile-title>@ame_bazaar</strong><div class="ame-social-feed-instagram-stats"><span><b data-stat-posts>—</b> posts</span><span><b data-stat-followers>—</b> followers</span><span><b data-stat-following>—</b> following</span></div><p data-profile-bio>AME Bazaar · Family Garment Store</p></div></div>
				<div class="ame-social-feed-posts ame-social-feed-instagram-grid" data-posts><div class="ame-social-feed-loading">Loading live Instagram posts…</div></div>
			</article>
		</div>

		<div class="ame-social-feed-status" data-feed-status><span class="dot"></span> Live feed · checking for new posts every 5 minutes</div>
	</div>
</section>

<style>
.ame-social-feed-section{padding:5rem 0;background:linear-gradient(180deg,#f7f8fb 0%,#fff 100%)}
.ame-social-feed-header{max-width:800px;margin:0 auto 2.5rem;text-align:center}.ame-social-feed-live{display:inline-flex;align-items:center;gap:.45rem;margin-bottom:.55rem;font-size:.7rem;font-weight:900;letter-spacing:.16em;color:#b08a32}.ame-social-feed-live span,.ame-social-feed-status .dot{width:7px;height:7px;border-radius:50%;background:#16a34a;box-shadow:0 0 0 4px rgba(22,163,74,.1)}.ame-social-feed-header .ame-h2{margin-bottom:.6rem;color:var(--ame-color-navy);font-weight:850}.ame-social-feed-header .ame-body{max-width:700px;margin:auto;color:var(--ame-color-slate)}
.ame-social-feed-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1.5rem;align-items:start}.ame-social-feed-card{min-width:0;overflow:hidden;background:#fff;border:1px solid rgba(15,23,42,.09);border-radius:20px;box-shadow:0 18px 50px rgba(15,23,42,.09)}.ame-social-feed-card-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1rem 1.1rem;border-bottom:1px solid rgba(15,23,42,.07)}.ame-social-feed-brand{display:flex;align-items:center;gap:.7rem;min-width:0}.ame-social-feed-brand strong{display:block;color:#111827;font-size:.95rem}.ame-social-feed-brand small{display:block;margin-top:.15rem;color:#64748b;font-size:.72rem}.ame-social-feed-brand-icon,.ame-social-feed-profile-icon{display:grid;place-items:center;flex:0 0 42px;width:42px;height:42px;border-radius:12px;color:#fff;font-weight:900}.ame-social-feed-brand-icon.facebook,.ame-social-feed-profile-icon.facebook{background:#1877f2;font-family:Arial,sans-serif}.ame-social-feed-brand-icon{font-size:1.45rem}.ame-social-feed-brand-icon.instagram,.ame-social-feed-profile-icon.instagram{background:linear-gradient(135deg,#f58529,#dd2a7b 52%,#8134af 82%,#515bd4)}.ame-social-feed-brand-icon.instagram{font-size:1.55rem}.ame-social-feed-follow{display:inline-flex;align-items:center;justify-content:center;min-height:34px;padding:0 .85rem;border-radius:999px;text-decoration:none!important;font-size:.75rem;font-weight:850;white-space:nowrap}.ame-social-feed-follow.facebook{background:#1877f2;color:#fff!important}.ame-social-feed-follow.instagram{background:#111827;color:#fff!important}
.ame-social-feed-facebook-cover{height:82px;background:linear-gradient(115deg,#1877f2 0%,#60a5fa 52%,#dbeafe 100%)}.ame-social-feed-facebook-profile-row{display:flex;align-items:center;gap:.8rem;margin-top:-25px;padding:0 1.1rem 1rem}.ame-social-feed-facebook-profile-row .ame-social-feed-profile-icon{border:4px solid #fff;border-radius:50%;box-shadow:0 4px 14px rgba(15,23,42,.15)}.ame-social-feed-facebook-profile-row strong{display:block;font-size:.95rem;color:#111827}.ame-social-feed-facebook-profile-row small{display:block;margin-top:.18rem;font-size:.72rem;color:#64748b}.ame-social-feed-instagram-profile{display:flex;align-items:center;gap:1rem;padding:1.05rem 1.1rem;border-bottom:1px solid rgba(15,23,42,.07)}.ame-social-feed-instagram-profile .ame-social-feed-profile-icon{border-radius:50%;font-size:1.8rem}.ame-social-feed-instagram-details{min-width:0}.ame-social-feed-instagram-details>strong{display:block;color:#111827;font-size:.98rem}.ame-social-feed-instagram-stats{display:flex;flex-wrap:wrap;gap:.75rem;margin-top:.32rem;color:#64748b;font-size:.7rem}.ame-social-feed-instagram-stats b{color:#111827}.ame-social-feed-instagram-details p{margin:.3rem 0 0;color:#475569;font-size:.72rem}
.ame-social-feed-posts{min-height:300px}.ame-social-feed-post{border-bottom:1px solid rgba(15,23,42,.08)}.ame-social-feed-post:last-child{border-bottom:0}.ame-social-feed-post-copy{padding:.9rem 1rem .7rem;color:#334155;font-size:.8rem;line-height:1.5;white-space:pre-line}.ame-social-feed-post-image-wrap{overflow:hidden;background:#f1f5f9}.ame-social-feed-post-image{display:block;width:100%;max-height:430px;object-fit:cover}.ame-social-feed-post-meta{display:flex;justify-content:space-between;gap:.7rem;padding:.65rem 1rem .85rem;color:#64748b;font-size:.68rem}.ame-social-feed-post-meta a{color:#475569;text-decoration:none;font-weight:800}.ame-social-feed-instagram-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:3px;min-height:0}.ame-social-feed-instagram-tile{position:relative;display:block;aspect-ratio:1;overflow:hidden;background:#f1f5f9}.ame-social-feed-instagram-tile img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .25s ease}.ame-social-feed-instagram-tile:hover img{transform:scale(1.04)}.ame-social-feed-instagram-tile:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 60%,rgba(0,0,0,.28));pointer-events:none}.ame-social-feed-instagram-tile-label{position:absolute;z-index:1;left:.5rem;bottom:.4rem;color:#fff;font-size:.62rem;font-weight:800;text-shadow:0 1px 4px rgba(0,0,0,.45)}
.ame-social-feed-loading,.ame-social-feed-empty,.ame-social-feed-error{display:grid;place-items:center;min-height:300px;padding:2rem;text-align:center;color:#64748b;font-size:.82rem;line-height:1.5}.ame-social-feed-empty a,.ame-social-feed-error a{color:#334155;font-weight:800}.ame-social-feed-instagram-grid .ame-social-feed-loading,.ame-social-feed-instagram-grid .ame-social-feed-empty,.ame-social-feed-instagram-grid .ame-social-feed-error{grid-column:1/-1}.ame-social-feed-status{display:flex;align-items:center;justify-content:center;gap:.5rem;min-height:1.2rem;margin-top:.8rem;color:#94a3b8;font-size:.7rem}
@media(max-width:900px){.ame-social-feed-grid{grid-template-columns:1fr;max-width:680px;margin:auto}}@media(max-width:560px){.ame-social-feed-section{padding:4rem 0}.ame-social-feed-card-head{padding:.85rem}.ame-social-feed-brand-icon,.ame-social-feed-profile-icon{width:36px;height:36px;flex-basis:36px}.ame-social-feed-brand strong{font-size:.88rem}.ame-social-feed-follow{min-height:32px;padding-inline:.7rem;font-size:.7rem}}
</style>

<script>
(function(){
	var section=document.querySelector('.ame-social-feed-section[data-social-feed-api]');
	if(!section||section.dataset.socialFeedReady==='1')return;section.dataset.socialFeedReady='1';
	var endpoint=section.getAttribute('data-social-feed-api'),fb=section.querySelector('[data-social-card="facebook"]'),ig=section.querySelector('[data-social-card="instagram"]'),status=section.querySelector('[data-feed-status]');
	function val(o,keys,f){for(var i=0;i<keys.length;i++){if(o&&o[keys[i]]!==undefined&&o[keys[i]]!==null&&o[keys[i]]!=='')return o[keys[i]]}return f}function arr(v){return Array.isArray(v)?v:[]}function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}function count(v){var n=Number(v);if(!isFinite(n))return v||'—';if(n>=1000000)return(n/1000000).toFixed(n%1000000?1:0)+'M';if(n>=1000)return(n/1000).toFixed(n%1000?1:0)+'K';return String(n)}function date(v){if(!v)return'';var d=new Date(v);return isNaN(d.getTime())?'':d.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}function media(o){return val(o,['media_url','image_url','full_picture','thumbnail_url','picture','display_url'],'')}function link(o,f){return val(o,['permalink','permalink_url','link','url'],f)}function text(o){return val(o,['caption','message','text','description'],'')}
	function normalize(p){var r=p&&p.data&&typeof p.data==='object'?p.data:p||{},i=r.instagram||{},f=r.facebook||{},ip=arr(val(i,['posts','media','items','data'],[])),fp=arr(val(f,['posts','feed','items','data'],[]));if(!ip.length)ip=arr(r.instagram_posts);if(!fp.length)fp=arr(r.facebook_posts);return{instagram:{profile:i.profile||r.instagram_profile||{},items:ip},facebook:{profile:f.profile||r.facebook_profile||{},items:fp}}}
	function renderFb(p,items){var name=val(p,['name','username','title'],'AME Bazaar'),followers=val(p,['followers_count','followers','fan_count'],'');fb.querySelectorAll('[data-profile-name]').forEach(function(e){e.textContent=name});fb.querySelector('[data-profile-title]').textContent=name;if(followers)fb.querySelector('[data-profile-stats]').textContent=count(followers)+' followers';var t=fb.querySelector('[data-posts]');if(!items.length){t.innerHTML='<div class="ame-social-feed-empty">No Facebook posts were returned by the live source.<br><a href="<?php echo esc_js( $facebook_url ); ?>" target="_blank" rel="noopener noreferrer">Open Facebook</a></div>';return}t.innerHTML=items.slice(0,3).map(function(o){var im=media(o),l=link(o,'<?php echo esc_js( $facebook_url ); ?>'),tx=text(o),d=date(val(o,['created_time','timestamp','published_at','date'],''));return'<div class="ame-social-feed-post">'+(tx?'<div class="ame-social-feed-post-copy">'+esc(tx)+'</div>':'')+(im?'<div class="ame-social-feed-post-image-wrap"><a href="'+esc(l)+'" target="_blank" rel="noopener noreferrer"><img class="ame-social-feed-post-image" loading="lazy" src="'+esc(im)+'" alt="AME Bazaar Facebook post"></a></div>':'')+'<div class="ame-social-feed-post-meta"><span>'+esc(d)+'</span><a href="'+esc(l)+'" target="_blank" rel="noopener noreferrer">View post ↗</a></div></div>'}).join('')}
	function renderIg(p,items){var u=val(p,['username','handle'],'ame_bazaar').replace(/^@/,''),posts=val(p,['media_count','posts','post_count'],''),followers=val(p,['followers_count','followers'],''),following=val(p,['follows_count','following_count','following'],''),bio=val(p,['biography','bio','description'],'AME Bazaar · Family Garment Store');ig.querySelectorAll('[data-profile-name]').forEach(function(e){e.textContent=u});ig.querySelector('[data-profile-title]').textContent='@'+u;ig.querySelector('[data-stat-posts]').textContent=count(posts);ig.querySelector('[data-stat-followers]').textContent=count(followers);ig.querySelector('[data-stat-following]').textContent=count(following);ig.querySelector('[data-profile-bio]').textContent=bio;var t=ig.querySelector('[data-posts]');if(!items.length){t.innerHTML='<div class="ame-social-feed-empty">No Instagram posts were returned by the live source.<br><a href="<?php echo esc_js( $instagram_url ); ?>" target="_blank" rel="noopener noreferrer">Open Instagram</a></div>';return}t.innerHTML=items.slice(0,9).map(function(o){var im=media(o),l=link(o,'<?php echo esc_js( $instagram_url ); ?>'),type=val(o,['media_type','type'],'');return'<a class="ame-social-feed-instagram-tile" href="'+esc(l)+'" target="_blank" rel="noopener noreferrer" aria-label="View Instagram post">'+(im?'<img loading="lazy" src="'+esc(im)+'" alt="AME Bazaar Instagram post">':'')+(type&&type!=='IMAGE'?'<span class="ame-social-feed-instagram-tile-label">'+esc(type.toLowerCase())+'</span>':'')+'</a>'}).join('')}
	function load(){fetch(endpoint+'?limit=9&_='+Date.now(),{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(function(p){var d=normalize(p);renderFb(d.facebook.profile,d.facebook.items);renderIg(d.instagram.profile,d.instagram.items);status.innerHTML='<span class="dot"></span> Live data · last checked '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}).catch(function(e){console.warn('AME Bazaar social feed:',e);fb.querySelector('[data-posts]').innerHTML='<div class="ame-social-feed-error">Facebook live feed is temporarily unavailable.<br><a href="<?php echo esc_js( $facebook_url ); ?>" target="_blank" rel="noopener noreferrer">Open Facebook</a></div>';ig.querySelector('[data-posts]').innerHTML='<div class="ame-social-feed-error">Instagram live feed is temporarily unavailable.<br><a href="<?php echo esc_js( $instagram_url ); ?>" target="_blank" rel="noopener noreferrer">Open Instagram</a></div>';status.innerHTML='<span class="dot"></span> Live feed temporarily unavailable · retrying automatically';})}
	load();setInterval(load,300000);
})();
</script>
